version: "3.8"
services:
  # aggregator: # C++
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/cpp/aggregator.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:main"
  #   image: "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:${TAG}"
  #   volumes:
  #     - ${MONO_DIR}/src/samples/cpp/aggregator:/root/ament_ws/src/aggregator

  aggregator: # PYTHON
    build:
      context: ..
      dockerfile: docker/samples/python/aggregator.Dockerfile
      cache_from:
        - "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:${TAG}"
        - "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:main"
    image: "${SAMPLES_PYTHON_AGGREGATOR_IMAGE:?}:${TAG}"
    volumes:
      - ${MONO_DIR}/src/samples/python/aggregator:/root/ament_ws/src/aggregator

  producer: # C++
    build:
      context: ..
      dockerfile: docker/samples/cpp/producer.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_PRODUCER_IMAGE:?}:${TAG}"
        - "${SAMPLES_CPP_PRODUCER_IMAGE:?}:main"
    image: "${SAMPLES_CPP_PRODUCER_IMAGE:?}:${TAG}"
    volumes:
      - ${MONO_DIR}/src/samples/cpp/producer:/root/ament_ws/src/producer

  # producer: # PYTHON
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/python/producer.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:main"
  #   image: "${SAMPLES_PYTHON_PRODUCER_IMAGE:?}:${TAG}"
  #   volumes:
  #     - ${MONO_DIR}/src/samples/python/producer:/root/ament_ws/src/producer

  transformer: # C++
    build:
      context: ..
      dockerfile: docker/samples/cpp/transformer.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:${TAG}"
        - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:main"
    image: "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:${TAG}"
    volumes:
      - ${MONO_DIR}/src/samples/cpp/transformer:/root/ament_ws/src/transformer

  # transformer: # PYTHON
  #   build:
  #     context: ..
  #     dockerfile: docker/samples/python/transformer.Dockerfile
  #     cache_from:
  #       - "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:${TAG}"
  #       - "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:main"
  #   image: "${SAMPLES_PYTHON_TRANSFORMER_IMAGE:?}:${TAG}"
  #   volumes:
  #     - ${MONO_DIR}/src/samples/python/transformer:/root/ament_ws/src/transformer
