services:
  foxglove:
    build:
      context: ..
      dockerfile: docker/vis_tools/foxglove.Dockerfile
      cache_from:
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:main"
    image: "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
    profiles: [deploy, develop]
    command: ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=${FOXGLOVE_BRIDGE_PORT:?}"]
    ports:
      - "${FOXGLOVE_BRIDGE_PORT:?}:${FOXGLOVE_BRIDGE_PORT:?}"
