planner_node:
  ros__parameters:
    map_topic: "/map"
    goal_topic: "/goal_pose"
    odom_topic: "/odom/filtered"
    path_topic: "/path"

    # Path Smoothing Params
    smoothing_factor: 0.2
    iterations: 20

    # Path start-end params
    goal_tolerance: 0.3
    plan_timeout_seconds: 30.0


