map_memory_node:
  ros__parameters:
    local_costmap_topic: "/costmap" # local costmap topic with which map memory node subscribes to
    odom_topic: "/odom/filtered" # odometry topic with which map memory node subscribes to
    map_topic: "/map" # map topic with which the map will be published to

    global_map:
      resolution: 0.4
      width: 80
      height: 80

      origin:
        position:
          x: -16.0 # given by -1 * width * resolution / 2
          y: -16.0 # given by -1 * height * resolution / 2
        orientation:
          w: 1.0

    distance: 1.5
