map_memory_node:
  ros__parameters:
    local_costmap_topic: "/costmap" # local costmap topic with which map memory node subscribes to
    odom_topic: "/odom/filtered" # odometry topic with which map memory node subscribes to
    map_topic: "/map" # map topic with which the map will be published to

    # ms, rate at which the map should be published
    # for simplicity, this is also the rate the A* planner plans at
    map_pub_rate: 3000
    # m, distance travelled by the robot at which the map will update
    update_distance: 1.5

    global_map:
      resolution: 0.5
      width: 60
      height: 60

      origin:
        position:
          x: -15.0 # given by -1 * width * resolution / 2
          y: -15.0 # given by -1 * height * resolution / 2
        orientation:
          w: 1.0
