costmap_node:
  ros__parameters:
    laserscan_topic: "/lidar" # laserscan topic with which costmap node subscribes to
    costmap_topic: "/costmap" # occupancy grid topic with which costmap node publishes the costmap to

    costmap:
      resolution: 0.40
      width: 120
      height: 120

      origin:
        position:
          x: -24.0 # given by -1 * width * resolution / 2
          y: -24.0 # given by -1 * height * resolution / 2
        orientation:
          w: 1.0
      
      inflation_radius: 1.5
